In [6]:
#Problem Statement:
#You work in XYZ Company as a Python. The company officials want you to build a python program.
#Tasks to be performed:
#1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
#Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
#[
# [5, 5, 5],
# [5, 5, 5],
# [5, 5, 5]
#]
import pandas as pd
import numpy as np
def add(a,b,c):
    s=np.full((a,b),c)
    return s
add(3,3,5)




array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
e=np.full((3,3),5)

In [9]:
e

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
#2. Create a method that takes n Numpy arrays of same dimensions sums them and return the 
#answer.
def add1(x,y,z):
  f=np.add(x,y,z)
  return f
  

In [24]:
x=np.array([10,20,30])
y=np.array([3,5,67])
z=np.array([2,5,12])
add1(x,y,z)



array([13, 25, 97])

In [25]:
add1(x,y,z)

array([13, 25, 97])

In [17]:
def add12(n):
    n=int(input())

In [19]:
add12(0)

25


In [20]:
add12

<function __main__.add12>

In [29]:
#3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
#numbers N and M. The method should return the top-left N X M sub matrix e.g:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
#top_left_sub_matrix (matrix, 2, 2) -> should return:
 #[
 #[1, 2]
 #[4, 5]
 #]
#Python Certification Course
#support@intellipaat.com - +91-7022374614 - US: 1-800-216-8930 (Toll Free)
matrix=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
#Doing matrix=np.array([1,2,3,4,5,6,7,8,9].reshape(3,3)) 
#is wrong n will give erros.





In [36]:
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
#def top_left(matrix,a,b)
def func1(arr,m,n):#matrix arr and m and n are dimensions
   mn=a1[:m,:n]#mn is variable for indexing in a1
   print(mn)#print indexed entries
a1=np.array([[3,4,5],[6,7,9],[1,2,3]])# a1 matrix definition
x=int(input("Enter the X dimension:"))# x and y are user input
y=int(input("Enter the Y dimension:"))
func1(a1,x,y)# function call
  

Enter the X dimension:3
Enter the Y dimension:3
[[3 4 5]
 [6 7 9]
 [1 2 3]]


In [190]:
#4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
#numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
# [
 #[1, 2, 3],
 #[4, 5, 6],
 #[7, 8, 9],
 #]
#sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
# [
# [5, 6]
# [8, 9]
# ]

def top_left(matrix,a,b):
  print(matrix[:a,:b])
top_left(matrix,2,2)


  


[[1 2]
 [4 5]]


In [196]:
def bottom_right(matrix,a,b):
  print(matrix[a:,b:])
bottom_right(matrix,1,1)


[[5 6]
 [8 9]]


In [67]:
def func1(arr,m,n):#matrix arr and m and n are dimensions
   mn=a1[:m,:n]#mn is variable for indexing in a1
   print(mn)#print indexed entries
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])# a1 matrix definition
x=int(input("Enter the X dimension:"))# x and y are user input
y=int(input("Enter the Y dimension:"))
func1(a1,x,y)# function call

Enter the X dimension:3
Enter the Y dimension:3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [199]:
#5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
#should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
#standard deviation as values:
 #[1, 1, 1]
#solution(arr) -> should return :
# {'mean': 1.0, 'std_dev': 0.0}
s=np.array([1,1,1])
def compute(s):
  m=np.mean(s)
  d=np.std(s)
  me=np.median(s)
  dict1={"mean":m,"standard":d,"median":me}
  return dict1
compute(s) 

{'mean': 1.0, 'median': 1.0, 'standard': 0.0}