In [ ]:
#Problem Statement:
#You work in XYZ Corporation as a Data Analyst. Your corporation has told you to use the numpy 
#package and do some tasks related to that:
#Tasks to be performed:
#1. Create a 3x3 matrix array with values ranging from 2 to 10.
import numpy as np
myarray=np.arange(2,11)


In [ ]:
myarray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#2. Create a numpy array having user input values and convert the integer type to the float type 
#of the elements of the array. For instance:
#Original array
#[1, 2, 3, 4]
#Array converted to a float type:
#[ 1. 2. 3. 4.]
array1=np.array([2,3,4,6])
array11=array1.astype(float)


In [ ]:
array11

array([2., 3., 4., 6.])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
#if np.array is not take
array2=[1,2,4,5]



In [ ]:
type(array2)

list

In [ ]:
#3. Write a Numpy program to append values to the end of an array. For instance:
#Original array:
#[10, 20, 30]
#After append values to the end of the array:
#[10 20 30 40 50 60 70 80 90]
array3=np.array([10,20,30])


In [ ]:
array3 #org. array

array([10, 20, 30])

In [ ]:
type(array3)

numpy.ndarray

In [ ]:
b=np.append(array3,[40,50,60,70,80,90])

In [ ]:
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
ar1=myarray.reshape(3,3)

In [ ]:
ar1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
b=np.append(array3,[40,50,60,70,80,90])


In [ ]:
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
b1=np.append([40,50,60,70,80,90],array3)

In [ ]:
b1

array([40, 50, 60, 70, 80, 90, 10, 20, 30])

In [ ]:
#4. Create two numpy arrays and add the elements of both the arrays and store the result in 
#sumArray.
c=np.array([1,3,5,7])
d=np.array([2,6,8,9])
sumArray=np.add(c,d)


In [ ]:
sumArray
#numpy array can be added only if there are same number of elements.

array([ 3,  9, 13, 16])

In [ ]:
#5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
#the following tasks:

myarray2=np.arange(10,100,10)



In [ ]:
myarray2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
array3=myarray2.reshape(3,3)

In [ ]:
array3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
#a. Extract the 1st row from the array.

array3[0]

array([10, 20, 30])

In [ ]:
#b. Extract the last element from the array.
array3[-1]

array([70, 80, 90])

In [ ]:
#b.Another way: Extract the last element from the array.
array3[2]

array([70, 80, 90])

In [ ]:
#c.for self understanding
array3[2,1]

80

In [ ]:
#c.for self understanding
array3[1,-1]

60

In [ ]:
array3[2,2]

90

In [ ]:
array3[0,0]

10

In [46]:
array3.item(0)

10

In [47]:
array3.item(2,1)

80

In [48]:
array3.item(2,-1)

90